/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import AccesoADatos.TratamientoData;
import Entidades.TiposTratamientos;
import Entidades.Tratamiento;
import javax.swing.JOptionPane;

/**
 *
 * @author gonza
 */
public class AgregarTratamiento extends javax.swing.JInternalFrame {

    private TratamientoData tratData = new TratamientoData();
    private Tratamiento tratamiento = null;
    private double importe = 0;
    private double importe2 = 0;

    public AgregarTratamiento() {
        initComponents();
        cargarCombo();
        jrbTarjeta.setSelected(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtCodigo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaDescripcion = new javax.swing.JTextArea();
        jrbTarjeta = new javax.swing.JRadioButton();
        jrbEfectivo = new javax.swing.JRadioButton();
        jtImporte = new javax.swing.JTextField();
        jrbActivo = new javax.swing.JRadioButton();
        jrbInactivo = new javax.swing.JRadioButton();
        jbSalir = new javax.swing.JButton();
        jbGuardar = new javax.swing.JButton();
        jbNuevo = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jcbTipo = new javax.swing.JComboBox<>();

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("TRATAMIENTO");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Codigo:");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Tipo:");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Descripcion:");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Importe:");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Estado:");

        jtCodigo.setBackground(new java.awt.Color(255, 255, 255));
        jtCodigo.setForeground(new java.awt.Color(0, 0, 0));
        jtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtCodigoKeyTyped(evt);
            }
        });

        jtaDescripcion.setBackground(new java.awt.Color(255, 255, 255));
        jtaDescripcion.setColumns(20);
        jtaDescripcion.setForeground(new java.awt.Color(0, 0, 0));
        jtaDescripcion.setLineWrap(true);
        jtaDescripcion.setRows(5);
        jtaDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtaDescripcionKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(jtaDescripcion);

        jrbTarjeta.setBackground(new java.awt.Color(204, 204, 255));
        jrbTarjeta.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jrbTarjeta.setForeground(new java.awt.Color(0, 0, 0));
        jrbTarjeta.setText("Tarjeta/otro");
        jrbTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbTarjetaActionPerformed(evt);
            }
        });

        jrbEfectivo.setBackground(new java.awt.Color(204, 204, 255));
        jrbEfectivo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jrbEfectivo.setForeground(new java.awt.Color(0, 0, 0));
        jrbEfectivo.setText("Efectivo");
        jrbEfectivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbEfectivoActionPerformed(evt);
            }
        });

        jtImporte.setBackground(new java.awt.Color(255, 255, 255));
        jtImporte.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jtImporte.setForeground(new java.awt.Color(0, 0, 0));
        jtImporte.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtImporteFocusLost(evt);
            }
        });
        jtImporte.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtImporteKeyTyped(evt);
            }
        });

        jrbActivo.setBackground(new java.awt.Color(204, 204, 255));
        jrbActivo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jrbActivo.setForeground(new java.awt.Color(0, 0, 0));
        jrbActivo.setText("Activo");
        jrbActivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbActivoActionPerformed(evt);
            }
        });

        jrbInactivo.setBackground(new java.awt.Color(204, 204, 255));
        jrbInactivo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jrbInactivo.setForeground(new java.awt.Color(0, 0, 0));
        jrbInactivo.setText("Inactivo");
        jrbInactivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbInactivoActionPerformed(evt);
            }
        });

        jbSalir.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        jbGuardar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jbGuardar.setText("Guardar");
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });

        jbNuevo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jbNuevo.setText("Nuevo");
        jbNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevoActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("$");

        jcbTipo.setBackground(new java.awt.Color(255, 255, 255));
        jcbTipo.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtCodigo)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7)
                                .addGap(2, 2, 2)
                                .addComponent(jtImporte, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jrbEfectivo)
                                .addGap(18, 18, 18)
                                .addComponent(jrbTarjeta))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jbNuevo)
                                        .addGap(18, 18, 18)
                                        .addComponent(jbGuardar)
                                        .addGap(18, 18, 18)
                                        .addComponent(jbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jrbActivo)
                                        .addGap(18, 18, 18)
                                        .addComponent(jrbInactivo)))))))
                .addContainerGap(84, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(155, 155, 155))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jcbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jrbEfectivo)
                    .addComponent(jrbTarjeta)
                    .addComponent(jtImporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jrbActivo)
                    .addComponent(jrbInactivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSalir)
                    .addComponent(jbGuardar)
                    .addComponent(jbNuevo))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrbTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbTarjetaActionPerformed

        if (jrbTarjeta.isSelected() && tratamiento != null) {
            jrbEfectivo.setSelected(false);
            jtImporte.setText(tratamiento.getImporte() + "");
        } else if (jrbTarjeta.isSelected() && tratamiento == null) {
            jrbEfectivo.setSelected(false);
            jtImporte.setText(importe2 + "");

        }


    }//GEN-LAST:event_jrbTarjetaActionPerformed

    private void jrbInactivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbInactivoActionPerformed
        if (jrbInactivo.isSelected()) {
            jrbActivo.setSelected(false);
        }
    }//GEN-LAST:event_jrbInactivoActionPerformed

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed

        if (jtCodigo.getText().isEmpty() || jcbTipo.getSelectedItem() == null || jtaDescripcion.getText().isEmpty() || jtImporte.getText().isEmpty() || (!jrbActivo.isSelected() && !jrbInactivo.isSelected())) {
            JOptionPane.showMessageDialog(this, "Llene los espacios vacios.");
        } else {
            int codigo = Integer.parseInt(jtCodigo.getText());
            TiposTratamientos tipos = (TiposTratamientos) jcbTipo.getSelectedItem();
            String descripcion = jtaDescripcion.getText();
            importe = Double.parseDouble(jtImporte.getText());
            boolean activo = jrbActivo.isSelected();
            boolean inactivo = jrbInactivo.isSelected();

            tratamiento = tratData.buscarTratamiento(codigo);

            if (activo && tratamiento == null) {
                tratData.agregarTratamiento(new Tratamiento(tipos, descripcion, importe, activo));
                jtCodigo.setText("");
                jcbTipo.setSelectedItem(null);
                jtImporte.setText("");
                jtaDescripcion.setText("");
                jrbTarjeta.setSelected(true);
                jrbEfectivo.setSelected(false);
                jrbActivo.setSelected(false);
                jrbInactivo.setSelected(false);
            } else if (inactivo && tratamiento == null) {
                tratData.agregarTratamiento(new Tratamiento(tipos, descripcion, importe, inactivo));
                jtCodigo.setText("");
                jcbTipo.setSelectedItem(null);
                jtImporte.setText("");
                jtaDescripcion.setText("");
                jrbTarjeta.setSelected(true);
                jrbEfectivo.setSelected(false);
                jrbActivo.setSelected(false);
                jrbInactivo.setSelected(false);
            }else{
                JOptionPane.showMessageDialog(this, "El tratamiento ya existe. Si desea modificarlo vaya al listado de tratamiento.");
            }
        }

//        if (tratamiento != null) {
//            tratamiento.setTipo(tipos);
//            tratamiento.setDescripcion(descripcion);
//            tratamiento.setImporte(importe);
//            if (activo) {
//                tratamiento.setEstado(true);
//            } else {
//                tratamiento.setEstado(false);
//            }
//            int op = JOptionPane.showConfirmDialog(this, "El tratamiento ya existe. Quiere modificarlo?");
//            if (op == 0) {
//                tratData.modificarTratamiento(tratamiento);
//                jtCodigo.setText("");
//                jcbTipo.setSelectedItem(null);
//                jtImporte.setText("");
//                jtaDescripcion.setText("");
//                jrbTarjeta.setSelected(false);
//                jrbActivo.setSelected(false);
//                jrbInactivo.setSelected(false);
//            } else {
//                jtCodigo.setText("");
//                jcbTipo.setSelectedItem(null);
//                jtImporte.setText("");
//                jtaDescripcion.setText("");
//                jrbTarjeta.setSelected(false);
//                jrbActivo.setSelected(false);
//                jrbInactivo.setSelected(false);
//            }
//                jtCodigo.setText("");
//                jcbTipo.setSelectedItem(null);
//                jtImporte.setText("");
//                jtaDescripcion.setText("");
//                jrbTarjeta.setSelected(false);
//                jrbActivo.setSelected(false);
//                jrbInactivo.setSelected(false);
//        }

    }//GEN-LAST:event_jbGuardarActionPerformed

    private void jrbEfectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbEfectivoActionPerformed
        importe = Double.parseDouble(jtImporte.getText());
        if (jrbEfectivo.isSelected() && tratamiento != null) {
            jrbTarjeta.setSelected(false);
            importe = tratData.importeContado(tratamiento);
            jtImporte.setText(importe + "");
        } else if (jrbEfectivo.isSelected() && tratamiento == null) {
            jrbTarjeta.setSelected(false);
            double descuento = (10 * importe) / 100;
            double importeTotal = importe - descuento;
            jtImporte.setText(importeTotal + "");
        }


    }//GEN-LAST:event_jrbEfectivoActionPerformed

    private void jrbActivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbActivoActionPerformed
        if (jrbActivo.isSelected()) {
            jrbInactivo.setSelected(false);
        }
    }//GEN-LAST:event_jrbActivoActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jtImporteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtImporteFocusLost
        try {
            importe2 = Double.parseDouble(jtImporte.getText());
        } catch (NumberFormatException e) {

        }


    }//GEN-LAST:event_jtImporteFocusLost

    private void jbNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoActionPerformed
        jtCodigo.setText("");
        jcbTipo.setSelectedItem(null);
        jtImporte.setText("");
        jtaDescripcion.setText("");
        jrbTarjeta.setSelected(true);
        jrbEfectivo.setSelected(false);
        jrbActivo.setSelected(false);
        jrbInactivo.setSelected(false);
        
        
//                try {
//            int codigo = Integer.parseInt(jtCodigo.getText());
//
//            tratamiento = tratData.buscarTratamiento(codigo);
//
//            if (tratamiento != null) {
//                int op = JOptionPane.showConfirmDialog(this, "Tramiento encontrado. Desea cargarlo?");
//                if (op == 0) {
//                    jcbTipo.setSelectedItem(tratamiento.getTipo());
//
//                    jtaDescripcion.setText(tratamiento.getDescripcion());
//                    jtImporte.setText(tratamiento.getImporte() + "");
//                    jtImporte.setEditable(false);
//                    jrbTarjeta.setSelected(true);
//                    if (tratamiento.isEstado()) {
//                        jrbActivo.setSelected(true);
//                    } else {
//                        jrbInactivo.setSelected(true);
//                    }
//                } else {
//
//                    jtCodigo.setText("");
//                    jcbTipo.setSelectedItem(null);
//                    jtImporte.setText("");
//                    jtaDescripcion.setText("");
//                    jrbTarjeta.setSelected(false);
//                    jrbActivo.setSelected(false);
//                    jrbInactivo.setSelected(false);
//
//                }
//            } else {
//                jtImporte.setEditable(true);
//            }
//        } catch (NumberFormatException e) {
//            JOptionPane.showMessageDialog(this, "Ingrese un numero");
//        }
        
    }//GEN-LAST:event_jbNuevoActionPerformed

    private void jtCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtCodigoKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {//si el caracter no es un numero
            evt.consume();          //no permite escribir
        }
    }//GEN-LAST:event_jtCodigoKeyTyped

    private void jtaDescripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtaDescripcionKeyTyped


    }//GEN-LAST:event_jtaDescripcionKeyTyped

    private void jtImporteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtImporteKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            evt.consume();          
        }
    }//GEN-LAST:event_jtImporteKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JButton jbNuevo;
    private javax.swing.JButton jbSalir;
    private javax.swing.JComboBox<TiposTratamientos> jcbTipo;
    private javax.swing.JRadioButton jrbActivo;
    private javax.swing.JRadioButton jrbEfectivo;
    private javax.swing.JRadioButton jrbInactivo;
    private javax.swing.JRadioButton jrbTarjeta;
    private javax.swing.JTextField jtCodigo;
    private javax.swing.JTextField jtImporte;
    private javax.swing.JTextArea jtaDescripcion;
    // End of variables declaration//GEN-END:variables

    public void cargarCombo() {
        jcbTipo.addItem(null);
        jcbTipo.addItem(TiposTratamientos.BAÑOYCORTE);
        jcbTipo.addItem(TiposTratamientos.CIRUGIA);
        jcbTipo.addItem(TiposTratamientos.CONTROL);
        jcbTipo.addItem(TiposTratamientos.CURACIONES);
        jcbTipo.addItem(TiposTratamientos.ENFERMEDAD);
        jcbTipo.addItem(TiposTratamientos.MEDICACION);
        jcbTipo.addItem(TiposTratamientos.URGENCIA);
        jcbTipo.addItem(TiposTratamientos.VACUNACION);

    }
}
