/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import AccesoADatos.ClienteData;
import Entidades.Cliente;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author gonza
 */
public class ListadoClientes extends javax.swing.JInternalFrame {

    private ClienteData clienData = new ClienteData();

    public DefaultTableModel modelo = new DefaultTableModel() {

        public boolean filasColumnas(int filas, int columnas) {
            return false;
        }
    };

    public ListadoClientes() {
        initComponents();
        armarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jrbActivos = new javax.swing.JRadioButton();
        jrbInactivos = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtTabla = new javax.swing.JTable();
        jbSalir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jrbActivos.setBackground(new java.awt.Color(204, 204, 255));
        jrbActivos.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jrbActivos.setForeground(new java.awt.Color(0, 0, 0));
        jrbActivos.setText("Mostrar activos");
        jrbActivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbActivosActionPerformed(evt);
            }
        });

        jrbInactivos.setBackground(new java.awt.Color(204, 204, 255));
        jrbInactivos.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jrbInactivos.setForeground(new java.awt.Color(0, 0, 0));
        jrbInactivos.setText("Mostrar inactivos");
        jrbInactivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbInactivosActionPerformed(evt);
            }
        });

        jtTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtTabla);

        jbSalir.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("LISTADO DE CLIENTES");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbInactivos, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jrbActivos)
                        .addGap(212, 212, 212)))
                .addGap(135, 135, 135))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(183, 183, 183))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbActivos)
                    .addComponent(jrbInactivos))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbSalir)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrbInactivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbInactivosActionPerformed

        if (jrbInactivos.isSelected()) {
            jrbActivos.setSelected(false);
        }else{
            jrbInactivos.setSelected(true);
        }
        
        modelo.setRowCount(0);
        for (Cliente cliente : clienData.listarClientes()) {

            if (!cliente.isEstado()) {
                modelo.addRow(new Object[]{cliente.getIdCliente(), cliente.getDocumento(), cliente.getCabezaDeFamilia(), cliente.getDireccion(), cliente.getTelefono(), cliente.getPersonaAlternativa(), cliente.getTelefonoAlternativo(), cliente.isEstado()});
            }
        }

    }//GEN-LAST:event_jrbInactivosActionPerformed

    private void jrbActivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbActivosActionPerformed

        if (jrbActivos.isSelected()) {
            jrbInactivos.setSelected(false);
        }else{
            jrbActivos.setSelected(true);
        }
        
        modelo.setRowCount(0);
        for (Cliente cliente : clienData.listarClientes()) {

            if (cliente.isEstado()) {
                modelo.addRow(new Object[]{cliente.getIdCliente(), cliente.getDocumento(), cliente.getCabezaDeFamilia(), cliente.getDireccion(), cliente.getTelefono(), cliente.getPersonaAlternativa(), cliente.getTelefonoAlternativo(), cliente.isEstado()});
            }
        }


    }//GEN-LAST:event_jrbActivosActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        
        this.dispose();
        
    }//GEN-LAST:event_jbSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbSalir;
    private javax.swing.JRadioButton jrbActivos;
    private javax.swing.JRadioButton jrbInactivos;
    private javax.swing.JTable jtTabla;
    // End of variables declaration//GEN-END:variables

    public void armarTabla() {

        modelo.addColumn("ID");
        modelo.addColumn("DNI");
        modelo.addColumn("Apellido y Nombre");
        modelo.addColumn("Direccion");
        modelo.addColumn("Telefono");
        modelo.addColumn("Persona Alternativa");
        modelo.addColumn("Telefono Alternativo");
        modelo.addColumn("Estado");
        jtTabla.setModel(modelo);

        // Supongamos que "table" es el nombre de tu tabla
        //javax.swing.table.TableColumn column = table.getColumnModel().getColumn(columnIndex); // Reemplaza "columnIndex" con el índice de la columna que deseas ajustar
        //column.setPreferredWidth(newWidth); // Reemplaza "newWidth" con el nuevo ancho deseado
       TableColumn column = jtTabla.getColumnModel().getColumn(0);
//        column.setPreferredWidth(160);
      // column = jtTabla.getColumnModel().getColumn(0);
        column.setPreferredWidth(25);
//        column = jtTabla.getColumnModel().getColumn(1);
//        column.setPreferredWidth(40);
//        column = jtTabla.getColumnModel().getColumn(3);
//        column.setPreferredWidth(90);
//        column = jtTabla.getColumnModel().getColumn(5);
//        column.setPreferredWidth(160);
//        column = jtTabla.getColumnModel().getColumn(6);
//        column.setPreferredWidth(160);
        column = jtTabla.getColumnModel().getColumn(7);
        column.setPreferredWidth(40);

    }

}
